# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  #config.vm.box = "ubuntu/disco64"
  #config.vm.box = "ubuntu/eoan64"
  #config.vm.box = "ubuntu/focal64"

  config.vm.box_check_update = false
  config.ssh.insert_key = false

  config.vm.hostname= "ubuntudev"

  config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.synced_folder "../../../", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y golang
  SHELL
end
