version: '3'

tasks:
  env:
    desc: Install environment
    cmds:
      - export GOPATH=~/dev/languages/go/grpc
      - export GOROOT=/opt/homebrew/Cellar/go/1.18.2/libexec
      - export PATH="$PATH:$(go env GOPATH)/bin"

  run-server:
    desc: Run the go binary.
    cmds:
      - go run src/server/server.go {{.CLI_ARGS}}
    deps:
      - env

  run-client:
    desc: Run the go binary.
    cmds:
      - go run src/client/client.go {{.CLI_ARGS}}
    deps:
      - env

  gen-grpc:
    desc: Regenerate GRPC files
    cmds:
      - ../data/protoc/bin/protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative src/routeguide/route_guide.proto
