version: '3'

tasks:
  env:
    desc: Install environment
    cmds:
      - export GOPATH=~/dev/languages/go/grpc
      - export GOROOT=/opt/homebrew/Cellar/go/1.18.2/libexec
      - export PATH="$PATH:$(go env GOPATH)/bin"

  build:
    desc: Build the go binary.
    cmds:
      -  go build -v -o bin/greeter_server src/greeter_server/main.go 
      -  go build -v -o bin/greeter_client src/greeter_client/main.go 
    deps:
      - env
  
  run-server:
    desc: Run the go binary.
    cmds:
      - go run src/greeter_server/main.go
    deps:
      - env

  run-client:
    desc: Run the go binary.
    cmds:
      - go run src/greeter_client/main.go {{.CLI_ARGS}}
    deps:
      - env

  install-protoc:
    desc: Install protoc
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      - export PATH="$PATH:$(go env GOPATH)/bin"

  gen-grpc:
    desc: Regenerate GRPC files
    cmds:
      - ../data/protoc/bin/protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative src/helloworld/helloworld.proto


